export const translations = {
    en: {
        Notification: {
            mark: "Mark all as read",
            noNotification: "No notifications yet...",
            Tag: "Notifications",
            user: "sent you a message",
            group: "sent a message in group",
            wlc1: "Welcome",
            wlc2: "to our library",
            whb: "What book are you reading?",
        },
        ChatBox: {  
            noConversation: "Please select a conversation...",
        },
        Navbar: {
            logout: "Logout",
            notifications: "Notifications",
            welcome: "Welcome",
            login: "Login",
            register: "Register",
            loginname: "Welcome",
        },
        login: {
            title: "Login",
            email: "Email",
            password: "Password",
            button: "Login",
            loading: "Getting you in...(My heart)",
            changeavt:"Change Avatar",
            changepass:"Change Password",
            oldpassword:"Old password",
            newpassword:"New password",
            confirmpassword:"Confirm password",
        },
        chat: {
            searchPlaceholder: "Search conversation",
            loading: "Loading chats...",
            noConversation: "No conversation selected yet..."
        },
        datetime: {
            yesterday: "yesterday",
            today: "today",
            last: "last",
            dayago: "day ago",
            weekago: "week ago",
            monthago: "month ago",
        },
        settings: {
            title: "Settings",
            account: "Account",
            editProfile: "Edit Profile",
            language: "Language",
            security: "Security",
            logout: "Logout",
            dangerZone: "Danger Zone",
            deleteAccount: "Delete Account",
            selectLanguage: "Select Language",
            confirmLogout: "Are you sure you want to log out?",
            cancel: "Cancel",
            confirmDelete: "Are you sure you want to delete your account? This action cannot be undone.",
            rpcmt: "Report Comment",
            rcmttitle: "Do you want to report this comment?",
            rp: "Report",
        },
        profile: {
            yourProfile: "Your Profile",
            posts: "Posts",
            followers: "Followers", 
            following: "Following",
            editProfile: "Edit Profile",
            books: "Books",
            noBooksYet: "No books shared yet",
            addFirstBook: "Add Your First Book",
            deleteAccount: "Delete Account",
        },
        book: {
            author: "Author",
            title: "Title",
            description: "Description",
            comments: "Comments",
            actor: "Actor",
            comment: "Comment",
            cancel: "Cancel",
            publishDate: "Published on", 
            edit: "Edit",
            delete: "Delete book",
            aldelete: "Are you sure you want to delete this book? This action cannot be undone.",
            sus: "Success",
            susdel: "Book deleted successfully",
            detail: "Book Detail",
            cmtsth: "Write your comment here...",
            morecmt: "Load more comments",
            nocmt: "No comments yet, let is the first to comment",
        },
        filter: {
            filter: "Filter",
            lup:"Latest Update",
            category: "Category",
            sortBy: "Sort by",
            anyt: "Anytime",
            tday: "Today",
            yday: "Yesterday",
            lweek: "Last Week",
            month: "Last Month",
            thmonth: "This Month",
            az: "A-Z",
            thyear: "This Year",
            thweek: "This Week",
            stby: "Sort by",
            time: "Time",
            title: "Title",
            author: "Author",
            rating: "Rating",
            de: "Descending",
            as: "Ascending",
            fil: "Filter",
        }
    },  
    vi: {
        Notification: {
            mark: "Đã đọc tất cả",
            noNotification: "Không có thông báo mới",
            Tag: "Thông báo",
            user: "đã gửi tin nhắn đến bạn",
            group: "đã gửi tin nhắn trong nhóm",
            wlc1: "Chào mừng",
            wlc2: "bạn đã đến với",
            whb: "Bạn đang đọc cuốn sách nào ?",
        },
        ChatBox:{
            noConversation: "Vui lòng chọn cuộc trò chuyện...",
        },
        Navbar: {
            logout: "Đăng xuất",
            notifications: "Thông báo",
            welcome: "Chào mừng",
            login: "Đăng nhập",
            register: "Đăng ký",
            loginname: "Xin chào",
        },
        login: {
            title: "Đăng nhập",
            email: "Email",
            password: "Mật khẩu",
            button: "Đăng nhập",
            loading: "Đang đăng nhập...",
            changeavt:"Đổi Ảnh Đại Diện",
            changepass:"Đổi Mật Khẩu",
            oldpassword:"Nhập mật khẩu cũ",
            newpassword:"Nhập mật khẩu mới",
            confirmpassword:"Xác nhận mật khẩu mới",
        },
        chat: {
            searchPlaceholder: "Tìm kiếm cuộc trò chuyện",
            loading: "Đang tải...",
            noConversation: "Vui lòng chọn cuộc trò chuyện..."
        },
        datetime: {
            yesterday: "hôm qua",
            today: "hôm nay",
            last: "trước",
            dayago: "ngày trước",
            weekago: "tuần trước",
            monthago: "tháng trước",
        },
        settings: {
            title: "Cài đặt",
            account: "Tài khoản",
            editProfile: "Chỉnh sửa hồ sơ",
            language: "Ngôn ngữ",
            security: "Bảo mật",
            logout: "Đăng xuất",
            dangerZone: "Khu vực nguy hiểm",
            deleteAccount: "Xóa tài khoản",
            selectLanguage: "Chọn ngôn ngữ",
            confirmLogout: "Bạn có chắc chắn muốn đăng xuất không?",
            cancel: "Hủy",
            confirmDelete: "Bạn có chắc chắn muốn xóa tài khoản? Hành động này không thể hoàn tác.",
            rpcmt: "Báo cáo bình luận",
            rcmttitle: "Bạn có muốn báo cáo bình luận này không?",
            rp: "Báo cáo",
        },
        profile: {
            yourProfile: "Trang cá nhân của bạn",
            posts: "Bài viết",
            followers: "Người theo dõi",
            following: "Đang theo dõi",
            editProfile: "Chỉnh sửa hồ sơ",
            books: "Sách",
            noBooksYet: "Chưa chia sẻ cuốn sách nào",
            addFirstBook: "Chia sẻ cuốn sách đầu tiên của bạn",
            deleteAccount: "Xóa tài khoản",
        },
        book: {
            author: "Tác giả",
            title: "Tiêu đề",
            description: "Mô tả",
            comments: "Bình luận",
            cancel: "Hủy",
            actor: "Người bình luận",
            comment: "Bình luận", 
            publishDate: "Ngày xuất bản",
            edit: "Chỉnh sửa",
            delete: "Xóa sách",
            aldelete: "Bạn có chắc chắn muốn xóa cuốn sách này? Hành động này không thể hoàn tác.",
            sus: "Hoàn tất",
            susdel: "Xoá sách hoàn tất",
            detail: "Chi tiết sách",
            cmtsth: "Viết bình luận của bạn ở đây...",
            morecmt: "Tải thêm bình luận",
            nocmt: "Chưa có bình luận nào, hãy là người đầu tiên bình luận",
        },
        filter: {
            filter: "Bộ lọc",
            lup:"Cập nhật mới nhất",
            category: "Thể loại",
            sortBy: "Sắp xếp theo",
            anyt: "Bất kỳ lúc nào",
            tday: "Hôm nay",
            yday: "Hôm qua",
            lweek: "Tuần trước",
            month: "Tháng trước",
            thmonth: "Tháng này",
            az: "A-Z",
            thyear: "Năm này",
            thweek: "Tuần này",
            stby: "Sắp xếp theo",
            time: "Thời gian",
            title: "Tiêu đề",
            author: "Tác giả",
            rating: "Đánh giá",
            de: "Giảm dần",
            as: "Tăng dần",
            fil: "Lọc",

        }

        
    }
};