import { create } from "zustand";

export const translations = {
    en: {
        create:{
            title: "Add Book Recommandation",
            title2:"Share your favorite reads with orthers",
            title3: "Book title",
            title3placeholder: "Enter the book title",
            authorplaceholder: "Enter the author's name",
            yearplaceholder: "Enter the publish year",
            genreplaceholder: "Select the book genre",
            author: "Author",
            year: "Publish Year",
            genre: "Genre",
            des: "Description",
            add: "Add Book",
            loading: "Creating book...",
            loading1: "Loading book details...",
            success: "Book created successfully",
            error: "Error creating book",
            cancel: "Cancel",
            rating: "Your Rating",
            bimg: "Book Image",
            cap:"Caption",
            capplaceholder: "Write a caption for your book",
            selectimg: "Select Image",
            sub: "Submit",
            alertimg:"Pickture is over 7MB, please select another one",
            alertyear: "Please enter a valid year",
            alimgae: "Book image cannot be empty",
            error: "Error",
            done: "Done",
            close: "Close",
            fill: "Please fill all the fields",
            upa:"Book recommendation updated successfully",
            done: "Done",
            uedit:"Update Book",
            uplace: "Update Book Recommandation",
        },
        Notification: {
            mark: "Mark all as read",
            noNotification: "No notifications yet...",
            Tag: "Notifications",
            user: "sent you a message",
            group: "sent a message in group",
            wlc1: "Welcome",
            wlc2: "to our library",
            whb: "What book are you reading?",
        },
        ChatBox: {  
            noConversation: "Please select a conversation...",
        },
        Navbar: {
            logout: "Logout",
            notifications: "Notifications",
            welcome: "Welcome",
            login: "Login",
            register: "Register",
            loginname: "Welcome",
            home: "Home",
            profile: "Profile",
            search: "Search",
            noti: "Notifications",
        },
        login: {
            title: "Login",
            logout: "Logout",
            logoutcnf: "Are you sure you want to log out?",
            cancel: "Cancel",
            email: "Email",
            password: "Password",
            button: "Login",
            loading: "Getting you in...(My heart)",
            changeavt:"Change Avatar",
            changepass:"Change Password",
            oldpassword:"Old password",
            newpassword:"New password",
            confirmpassword:"Confirm password",
            signup: "Sign Up",
            p1: "Please enter your email",
            p2: "Please enter your password",
            fp: "Forgot Password?",
            p3: "Please enter your old password",
            p4: "Please enter your new password",
            p5: "Please confirm your new password",
            p6: "Please enter your username",
            p7: "Password must be at least 6 characters",
            p8: "Passwords do not match",
            p9: "Please enter your username",
            p10: "Dont have an account?",
            send: "Send",
            code: "Verification Code",
            p11: "Enter verification code ",
            rs: "Resend Code",
            rsp:"Reset Password",
            p12:"Remmber your password?",
            p13:"Enter your email to receive a verification code",
            sigup: "Sign Up",
            username: "Username",
            p14:"Share your favorite books with others",
            p15:"You need to login to experience all the features of the app",
            error: "Error",
            invalid: "Invalid ",
            p16:"Please enter verification code and new password!",
            sus: "Success",
            p17: "Login successful",
            p18: "Registration successful, please login",
            p19: "Password changed successfully, please login",
            p20:"Invalid email",
            p21:"If your email exists in our system, a verification code has been sent to your email.",
            p22:"Could not send verification code, please try again later.",
            p23:"Something went wrong, please try again later.",
            p24:"Enter password again",
            p25:"Your account has been created. Please login to continue.",
            p26:"Already have an account?",



        },
        chat: {
            searchPlaceholder: "Search conversation",
            loading: "Loading chats...",
            noConversation: "No conversation selected yet..."
        },
        datetime: {
            yesterday: "yesterday",
            today: "today",
            last: "last",
            dayago: "day ago",
            weekago: "week ago",
            monthago: "month ago",
        },
        settings: {
            title: "Settings",
            account: "Account",
            editProfile: "Edit Profile",
            language: "Language",
            security: "Security",
            logout: "Logout",
            dangerZone: "Danger Zone",
            deleteAccount: "Delete Account",
            selectLanguage: "Select Language",
            confirmLogout: "Are you sure you want to log out?",
            cancel: "Cancel",
            confirmDelete: "Are you sure you want to delete your account? This action cannot be undone.",
            rpcmt: "Report Comment",
            rcmttitle: "Do you want to report this comment?",
            rp: "Report",
        },
        profile: {
            yourProfile: "Your Profile",
            posts: "Posts",
            followers: "Followers", 
            following: "Following",
            editProfile: "Edit Profile",
            books: "Books",
            noBooksYet: "No books shared yet",
            addFirstBook: "Add Your First Book",
            deleteAccount: "Delete Account",
            book: "Book",
            booked: "Published Books",
            bookload: "Loading books...",
            seeall: "See All Books",
            noin4: "No information available",
            searching: "Searching...",
            searchPlaceholder: "Search books by user, title or author",
            searchno: "No books found",
            user: "User",
            username: "Username",
            usernameplaceholder: "Enter your username",
            changep: "Change Password",
            save: "Save Changes",
            currentp:"Current Password",
            newp:"New Password",
            cnfp:"Confirm New Password",
            hidep:"Hide Password Change",
            editprofile: "Edit Profile",
            im1:"Image is too large!",
            im2:"Please select an image smaller than 7MB.",
            p1:"Permission to access camera roll is required!",
            a1:"Username cannot be empty",
            a2:"Current password is required",
            a3:"New password is required",
            a4:"Confirm password is required",
            a5:"New password and confirm password do not match",
            a6:"Password must be at least 6 characters",
            a7:"Failed to update profile",
            a8:"Profile updated successfully. You will be logged out for security reasons.",
            success: "Success",
            error: "Error",
            done: "Done",
            a9:"Something went wrong",
            p2:"Enter username",
            p4:"Enter current password",
            p5:"Enter new password",
            p6:"Confirm new password",

        },
        book: {
            author: "Author",
            title: "Title",
            description: "Description",
            comments: "Comments",
            actor: "Actor",
            comment: "Comment",
            cancel: "Cancel",
            publishDate: "Published on", 
            edit: "Edit",
            delete: "Delete book",
            aldelete: "Are you sure you want to delete this book? This action cannot be undone.",
            sus: "Success",
            susdel: "Book deleted successfully",
            detail: "Book Detail",
            cmtsth: "Write your comment here...",
            morecmt: "Load more comments",
            nocmt: "No comments yet, let is the first to comment",
        },
        filter: {
            filter: "Filter",
            lup:"Latest Update",
            category: "Category",
            sortBy: "Sort by",
            anyt: "Anytime",
            tday: "Today",
            yday: "Yesterday",
            lweek: "Last Week",
            month: "Last Month",
            thmonth: "This Month",
            az: "A-Z",
            thyear: "This Year",
            thweek: "This Week",
            stby: "Sort by",
            time: "Time",
            title: "Title",
            author: "Author",
            rating: "Rating",
            de: "Descending",
            as: "Ascending",
            fil: "Filter",
        },
        report: {
            content: "Inappropriate content",
            copyright: "Copyright infringement",
            misleading: "Misleading information",
            spam: "Spam or irrelevant content",
            other: "Other",
            qr: "Harassment or bullying",
            fake: "Fake account",
            nnt: "Hate speech",
            nvkph:"Inappropriate community behavior",
            error: "Error",
            back: "Back",
            success: "Report submitted successfully",
            successmsg: "Thank you for your report. We will review and take action as necessary.",
            unknow: "Unknown",
            writer: "Writer",
            user: "User",
            rpcontent: "Report Content",
            sltrp: "Select report reason",
            desplaceholder: "Enter details about the issue you are facing...",
            des: "Description (optional)",
            rpcnf: "Are you sure you want to report this content?",
            submit: "Submit Report",


        }
    },  
    vi: {
        create: {
            title: "Thêm sách yêu thích", 
            title2: "Chia sẻ những cuốn sách yêu thích của bạn với mọi người",
            title3: "Tiêu đề sách",
            title3placeholder: "Nhập tiêu đề sách",
            authorplaceholder: "Nhập tên tác giả",
            yearplaceholder: "Nhập năm xuất bản",
            genreplaceholder: "Chọn thể loại sách",
            author: "Tác giả",
            year: "Năm xuất bản",
            genre: "Thể loại",
            des: "Mô tả",
            add: "Thêm sách",
            loading: "Đang tạo sách...",
            success: "Tạo sách thành công",
            error: "Lỗi khi tạo sách",
            cancel: "Hủy",
            rating: "Đánh giá của bạn",
            bimg: "Hình ảnh sách",
            cap: "Cảm nghĩ của bạn",
            capplaceholder: "Viết chú thích cho cuốn sách của bạn",
            selectimg: "Chọn hình ảnh",
            sub: "Đăng",
            alertimg: "Hình ảnh vượt quá 7MB, vui lòng chọn hình ảnh khác",
            alertyear: "Vui lòng nhập năm hợp lệ",
            alimgae: "Hình ảnh sách không được để trống",
            error: "Lỗi",
            done: "Hoàn tất", 
            close: "Đóng",   
            fill: "Vui lòng điền đầy đủ thông tin",
            upa: "Cập nhật sách thành công",
            done: "Hoàn tất",
            loading1: "Đang tải chi tiết sách...",
            uedit:"Cập nhật sách",
            uplace: "Cập nhật sách yêu thích",
        },
        Notification: {
            mark: "Đã đọc tất cả",
            noNotification: "Không có thông báo mới",
            Tag: "Thông báo",
            user: "đã gửi tin nhắn đến bạn",
            group: "đã gửi tin nhắn trong nhóm",
            wlc1: "Chào mừng",
            wlc2: "bạn đã đến với",
            whb: "Bạn đang đọc cuốn sách nào ?",
        },
        ChatBox:{
            noConversation: "Vui lòng chọn cuộc trò chuyện...",
        },
        Navbar: {
            logout: "Đăng xuất",
            notifications: "Thông báo",
            welcome: "Chào mừng",
            login: "Đăng nhập",
            register: "Đăng ký",
            loginname: "Xin chào",
            home: "Trang chủ",
            profile: "Trang cá nhân",
            search: "Tìm kiếm",
            noti: "Thông báo",
        },
        login: {
            title: "Đăng nhập",
            email: "Email",
            password: "Mật khẩu",
            button: "Đăng nhập",
            loading: "Đang đăng nhập...",
            changeavt:"Đổi Ảnh Đại Diện",
            changepass:"Đổi Mật Khẩu",
            oldpassword:"Nhập mật khẩu cũ",
            newpassword:"Nhập mật khẩu mới",
            confirmpassword:"Xác nhận mật khẩu mới",
            logout: "Đăng xuất",
            logoutcnf: "Bạn có chắc chắn muốn đăng xuất không?",
            cancel: "Hủy",
            signup: "Đăng ký",
            p1: "Vui lòng nhập email của bạn",
            p2: "Vui lòng nhập mật khẩu của bạn",
            fp: "Quên mật khẩu?",
            p3: "Vui lòng nhập mật khẩu cũ",
            p4: "Vui lòng nhập mật khẩu mới",
            p5: "Vui lòng xác nhận mật khẩu mới",
            p6: "Vui lòng nhập tên người dùng",
            p7: "Mật khẩu phải có ít nhất 6 ký tự",
            p8: "Mật khẩu không khớp",
            p9: "Vui lòng nhập tên người dùng",
            p10: "Chưa có tài khoản?",
            send: "Gửi",
            code: "Mã xác minh",
            p11: "Nhập mã xác minh",
            rs: "Gửi lại mã",
            rsp: "Đặt lại mật khẩu",
            p12: "Nhớ mật khẩu?",
            p13: "Nhập email của bạn để nhận mã xác minh",
            sigup: "Đăng ký",
            username: "Tên tài khoản",
            p14: "Chia sẻ những cuốn sách yêu thích của bạn với mọi người",
            p15:"Bạn cần đăng nhập để được trải nghiệm đầy đủ các tính năng của ứng dụng",
            error: "Lỗi",
            invalid: "Không hợp lệ",
            p16: "Vui lòng nhập mã xác minh và mật khẩu mới!",
            sus: "Thành công",
            p17: "Đăng nhập thành công",
            p18: "Đăng ký thành công, vui lòng đăng nhập",
            p19: "Đổi mật khẩu thành công, vui lòng đăng nhập",
            p20: "Email không hợp lệ",
            p21: "Nếu email của bạn tồn tại trong hệ thống, mã xác minh đã được gửi đến email của bạn.",
            p22: "Không thể gửi mã xác minh, vui lòng thử lại sau.",
            p23: "Đã xảy ra lỗi, vui lòng thử lại sau.",
            p24: "Nhập lại mật khẩu",
            p25:"Tài khoản của bạn đã được tạo. Vui lòng đăng nhập để tiếp tục.",
            p26: "Đã có tài khoản?",



        },
        chat: {
            searchPlaceholder: "Tìm kiếm cuộc trò chuyện",
            loading: "Đang tải...",
            noConversation: "Vui lòng chọn cuộc trò chuyện..."
        },
        datetime: {
            yesterday: "hôm qua",
            today: "hôm nay",
            last: "trước",
            dayago: "ngày trước",
            weekago: "tuần trước",
            monthago: "tháng trước",
        },
        settings: {
            title: "Cài đặt",
            account: "Tài khoản",
            editProfile: "Chỉnh sửa hồ sơ",
            language: "Ngôn ngữ",
            security: "Bảo mật",
            logout: "Đăng xuất",
            dangerZone: "Khu vực nguy hiểm",
            deleteAccount: "Xóa tài khoản",
            selectLanguage: "Chọn ngôn ngữ",
            confirmLogout: "Bạn có chắc chắn muốn đăng xuất không?",
            cancel: "Hủy",
            confirmDelete: "Bạn có chắc chắn muốn xóa tài khoản? Hành động này không thể hoàn tác.",
            rpcmt: "Báo cáo bình luận",
            rcmttitle: "Bạn có muốn báo cáo bình luận này không?",
            rp: "Báo cáo",
        },
        profile: {
            yourProfile: "Trang cá nhân của bạn",
            posts: "Bài viết",
            followers: "Người theo dõi",
            following: "Đang theo dõi",
            editProfile: "Chỉnh sửa hồ sơ",
            books: "Sách",
            noBooksYet: "Chưa chia sẻ cuốn sách nào",
            addFirstBook: "Chia sẻ cuốn sách đầu tiên của bạn",
            deleteAccount: "Xóa tài khoản",
            book: "Sách",
            booked: "Sách đã đăng",
            bookload: "Đang tải sách...",
            seeall: "Xem tất cả sách",
            noin4: "Không có thông tin nào",
            searching: "Đang tìm kiếm...",
            searchPlaceholder: "Tìm kiếm sách theo người dùng, tiêu đề hoặc tác giả",
            searchno: "Không tìm thấy sách nào",
            username: "Tên người dùng",
            usernameplaceholder: "Nhập tên người dùng",
            changep: "Đổi mật khẩu",
            save: "Lưu thay đổi",
            currentp:"Mật khẩu hiện tại",
            newp:"Mật khẩu mới",
            cnfp:"Xác nhận mật khẩu mới",
            hidep:"Ẩn thay đổi mật khẩu",
            editprofile: "Chỉnh sửa hồ sơ",
            im1:"Hình ảnh quá lớn!",
            im2:"Vui lòng chọn hình ảnh nhỏ hơn 7MB.",
            p1:"Cần quyền truy cập vào thư viện ảnh!",
            a1:"Tên người dùng không được để trống",
            a2:"Mật khẩu hiện tại là bắt buộc",
            a3:"Mật khẩu mới là bắt buộc",
            a4:"Xác nhận mật khẩu là bắt buộc",
            a5:"Mật khẩu mới và xác nhận mật khẩu không khớp",
            a6:"Mật khẩu phải có ít nhất 6 ký tự",
            a7:"Cập nhật hồ sơ không thành công",
            a8:"Hồ sơ đã được cập nhật thành công. Bạn sẽ được đăng xuất vì lý do bảo mật.",
            success: "Thành công",
            error: "Lỗi",
            done: "Hoàn tất",
            a9: "Đã xảy ra lỗi",
            p2: "Nhập tên người dùng",
            p4: "Nhập mật khẩu hiện tại",
            p5: "Nhập mật khẩu mới",
            p6: "Xác nhận mật khẩu mới",
            





        },
        book: {
            author: "Tác giả",
            title: "Tiêu đề",
            description: "Mô tả",
            comments: "Bình luận",
            cancel: "Hủy",
            actor: "Người bình luận",
            comment: "Bình luận", 
            publishDate: "Ngày xuất bản",
            edit: "Chỉnh sửa",
            delete: "Xóa sách",
            aldelete: "Bạn có chắc chắn muốn xóa cuốn sách này? Hành động này không thể hoàn tác.",
            sus: "Hoàn tất",
            susdel: "Xoá sách hoàn tất",
            detail: "Chi tiết sách",
            cmtsth: "Viết bình luận của bạn ở đây...",
            morecmt: "Tải thêm bình luận",
            nocmt: "Chưa có bình luận nào, hãy là người đầu tiên bình luận",
        },
        filter: {
            filter: "Bộ lọc",
            lup:"Cập nhật mới nhất",
            category: "Thể loại",
            sortBy: "Sắp xếp theo",
            anyt: "Bất kỳ lúc nào",
            tday: "Hôm nay",
            yday: "Hôm qua",
            lweek: "Tuần trước",
            month: "Tháng trước",
            thmonth: "Tháng này",
            az: "A-Z",
            thyear: "Năm này",
            thweek: "Tuần này",
            stby: "Sắp xếp theo",
            time: "Thời gian",
            title: "Tiêu đề",
            author: "Tác giả",
            rating: "Đánh giá",
            de: "Giảm dần",
            as: "Tăng dần",
            fil: "Lọc",

        },

        report: {
            content: "Nội dung không phù hợp",
            copyright: "Vi phạm bản quyền",
            misleading: "Thông tin sai lệch",
            spam: "Spam hoặc nội dung không liên quan",
            other: "Khác",
            qr: "Quấy rối hoặc bắt nạt",
            fake: "Tài khoản giả mạo",
            nnt: "Ngôn ngữ thù hận",
            nvkph:"Hành vi không phù hợp với cộng đồng",
            error: "Lỗi",
            back: "Quay lại",
            success: "Báo cáo thành công",
            successmsg: "Cảm ơn bạn đã báo cáo. Chúng tôi sẽ xem xét và xử lý trong thời gian sớm nhất.",
            unknow: "Không xác định",
            writer: "Tác giả",
            user: "Người dùng",
            rpcontent: "Báo cáo nội dung",
            sltrp: "Chọn lý do báo cáo",
            desplaceholder: "Nhập thông tin chi tiết về vấn đề bạn gặp phải...",
            des: "Mô tả (tùy chọn)",
            rpcnf: "Bạn có chắc chắn muốn báo cáo nội dung này không?",
            submit: "Gửi báo cáo",



            

        },

        
    }
};